- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: remove html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: create html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download web app
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/web.zip
    dest: /tmp

- name: Extract application
  ansible.builtin.unarchive:
    src: /tmp/web.zip
    dest: /usr/share/nginx/html
    remote_src: yes

# - name: copy roboshop configuration
#   ansible.builtin.copy:
#     src: roboshop.conf
#     dest: /etc/nginx/default.d/roboshop.conf

- name: copy roboshop configuration
  ansible.builtin.template:
    src: roboshop.conf.jinja2
    dest: /etc/nginx/default.d/roboshop.conf
  notify:
  - Restart nginx #Handlers: -running operations on change with keyword called notify
  #If a particular task is changing some configuration we need to restart of the server otherwise no need to restart the server

- name: start and enable nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes