- name: "stop {{component}}"
  tags:
  - deployment
  ansible.builtin.service:
    name: "{{component}}"
    state: stopped

- name: Recursively remove app directory
  tags:
  - deployment
  ansible.builtin.file:
    path: /app  #path: /app (removing  /*)
    state: absent
    #force: yes -Force: yes--> is likerm -rf
    #recurse: yes - recurse option is only when directory exists/available
