- name: install mysql client
  ansible.builtin.dnf:
    name: mysql
    state: present

- name: check cities schema exists or not
  ansible.builtin.command: mysql -h {{MYSQL_HOST}} -uroot -pRoboShop@1 -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'"
  register: schema

- name: print output
  ansible.builtin.debug:
    msg: "schema output: {{schema}}"

- name: load cities data
  ansible.builtin.shell: "mysql -h {{MYSQL_HOST}} -uroot -pRoboShop@1 < /app/schema/{{component}}.sql" #Here we changed command to shell
  when: schema.stdout != "1"